// JSON Document
data = {"quizcontent": [
        {"question": "In Reverse Polish notation, expression A*B+C*D is written as",
        "image": "3.jpg",
        "correct": 1,
        "a1":"AB*CD*+",
        "a2":"A*BCD*+",
        "a3":"AB*CD+*",
        "a4":"A*B*CD+"},

        {"question": "SIMD represents an organization that ______________.",
        "image": "4.jpg",
        "correct": 3,
        "a1":"refers to a computer system capable of processing several programs at the same time.",
        "a2":"represents organization of single computer containing a control unit, processor unit and a memory unit.",
        "a3":"includes many processing units under the supervision of a common control unit",
        "a4":"none of the above."},

        {"question": "Floating point representation is used to store",
        "image": "4.jpg",
        "correct": 3,
        "a1":"Boolean values",
        "a2":"whole numbers",
        "a3":"real integers",
        "a4":"integers"},

        {"question": "Suppose that a bus has 16 data lines and requires 4 cycles of 250 nsecs each to transfer data. The bandwidth of this bus would be 2 Megabytes/sec. If the cycle time of the bus was reduced to 125 nsecs and the number of cycles required for transfer stayed the same what would the bandwidth of the bus?",
        "image": "4.jpg",
        "correct": 4,
        "a1":"1 Megabyte/sec",
        "a2":"4 Megabytes/sec",
        "a3":"8 Megabytes/sec",
        "a4":"2 Megabytes/sec"},

        {"question": "Assembly language",
        "image": "4.jpg",
        "correct": 1,
        "a1":"uses alphabetic codes in place of binary numbers used in machine language.",
        "a2":"is the easiest language to write programs",
        "a3":"need not be translated into machine language",
        "a4":"None of these"},

        {"question": "In computers, subtraction is generally carried out by",
        "image": "4.jpg",
        "correct": 4,
        "a1":"9’s complement",
        "a2":"10’s complement",
        "a3":"1’s complement",
        "a4":"2’s complement"},

        {"question": "The amount of time required to read a block of data from a disk into memory is composed of seek time, rotational latency, and transfer time. Rotational latency refers to",
        "image": "4.jpg",
        "correct": 1,
        "a1":"the time its takes for the platter to make a full rotation",
        "a2":"the time it takes for the read-write head to move into position over the appropriate track",
        "a3":"the time it takes for the platter to rotate the correct sector under the head",
        "a4":"none of the above"},

        {"question": "What characteristic of RAM memory makes it not suitable for permanent storage?",
        "image": "4.jpg",
        "correct": 3,
        "a1":"too slow",
        "a2":"unreliable",
        "a3":"it is volatile",
        "a4":"too bulky"},

        {"question": "Computers use addressing mode techniques for _____________________.",
            "image": "4.jpg",
            "correct": 4,
            "a1":"giving programming versatility to the user by providing facilities as pointers to memory counters for loop control",
            "a2":"to reduce no. of bits in the field of instruction",
            "a3":"specifying rules for modifying or interpreting address field of the instruction",
            "a4":"All the above"},

        {"question": "The circuit used to store one bit of data is known as",
            "image": "4.jpg",
            "correct": 4,
            "a1":"Register",
            "a2":"Encoder",
            "a3":"Decoder",
            "a4":"Flip Flop"},
        
        {"question": "(2FAOC) 16 is equivalent to",
            "image": "4.jpg",
            "correct": 2,
            "a1":"(195 084) 10",
            "a2":"001011111010 0000 1100) 2",
            "a3":"Both (A) and (B)",
            "a4":"None of these"},
    
        {"question": "The average time required to reach a storage location in memory and obtain its contents is called the",
            "image": "4.jpg",
            "correct": 3,
            "a1":"seek time",
            "a2":"turnaround time",
            "a3":"access time",
            "a4":"transfer time"},

        {"question": "Which of the following is not a weighted code?",
            "image": "4.jpg",
            "correct": 2,
            "a1":"Decimal Number system",
            "a2":"Excess 3-cod",
            "a3":"Binary number System",
            "a4":"None of these"},

        {"question": "The idea of cache memory is based",
            "image": "4.jpg",
            "correct": 1,
            "a1":"on the property of locality of reference",
            "a2":"on the heuristic 90-10 rule",
            "a3":"on the fact that references generally tend to cluster",
            "a4":"all of the above"},
    
        {"question": "Which of the following is lowest in memory hierarchy?",
            "image": "4.jpg",
            "correct": 2,
            "a1":"Cache memory",
            "a2":"Secondary memory",
            "a3":"Registers",
            "a4":"RAM",
            "a5":"None of these"},

        {"question": "The addressing mode used in an instruction of the form ADD X Y, is",
            "image": "4.jpg",
            "correct": 3,
            "a1":"Absolute",
            "a2":"indirect",
            "a3":"index",
            "a4":"none of these"},
        
        {"question": "",
            "image": "4.jpg",
            "correct": 4,
            "a1":"",
            "a2":"",
            "a3":"",
            "a4":""},
    
        {"question": "If memory access takes 20 ns with cache and 110 ns with out it, then the ratio ( cache uses a 10 ns memory) is",
            "image": "4.jpg",
            "correct": 2,
            "a1":"93%",
            "a2":"90%",
            "a3":"88%",
            "a4":"87%"},

        {"question": "In a memory-mapped I/O system, which of the following will not be there?",
            "image": "4.jpg",
            "correct": 1,
            "a1":"LDA",
            "a2":"IN",
            "a3":"ADD",
            "a4":"OUT"},

        {"question": "In a vectored interrupt.",
            "image": "4.jpg",
            "correct": 2,
            "a1":"the branch address is assigned to a fixed location in memory.",
            "a2":"the interrupting source supplies the branch information to the processor through an interrupt vector.",
            "a3":"the branch address is obtained from a register in the processor",
            "a4":"none of the above"},

    ],
};
