// JSON Document
data = {"quizcontent": [
        {"question": "Which of the following words has stress on the first syllable?",
        "image": "3.jpg",
        "correct": 1,
        "a1":"Action",
        "a2":"about",
        "a3":"Adventure",
        "a4":"Aside"},

        {"question": "Which of the following words has the vowel (i:) sound in the initial accented position?",
        "image": "4.jpg",
        "correct": 2,
        "a1":"English",
        "a2":"Eager",
        "a3":"Interest",
        "a4":"Employ"},

        {"question": "Which of the following sentences has the correct word order?",
        "image": "4.jpg",
        "correct": 4,
        "a1":"This is extermely an interesting item",
        "a2":"This is quite diffreent a thing",
        "a3":"The all men came",
        "a4":"All the men came"},

        {"question": "Which of the following sentences has the correct use of comma?",
        "image": "4.jpg",
        "correct": 1,
        "a1":"He left, for she had hurt him.",
        "a2":"We had a picnic near the river, even through it was snowing heavily.",
        "a3":"She had hurt him and, she was glad.",
        "a4":"He did not want to leave nor did, she want him to go."},

        {"question": "The passive voice of women wear ornaments' is:",
        "image": "4.jpg",
        "correct": 4,
        "a1":"Ornaments were worn by women.",
        "a2":"Ornaments are worn by women.",
        "a3":"Ornaments are being worn by women.",
        "a4":"Ornaments were worn by women."},

        {"question": "A Monochromatic light source of power rating of 33W emits radition of wavelength 6000A, the number of photons emitted per secong around:",
        "image": "4.jpg",
        "correct": 4,
        "a1":"10^16",
        "a2":"10^18",
        "a3":"10^20",
        "a4":"10^22"},

        {"question": "As the forward-bias potential b.d. across a p-n junction is increased.",
        "image": "4.jpg",
        "correct": 1,
        "a1":"the current increase",
        "a2":"the current decrease",
        "a3":"There is no change in current",
        "a4":"the width of the deplection layer increases"},

        {"question": "Oxidation number of cobalt in K[Co(CO) 4] is:",
        "image": "4.jpg",
        "correct": 4,
        "a1":"+1",
        "a2":"+3",
        "a3":"-3",
        "a4":"-1"},

        {"question": "The charge required for the reduction of 1 mole of Cr2O2^- ions to Cr^3+ is:",
        "image": "4.jpg",
        "correct": 3,
        "a1":"1.5C",
        "a2":"2.0C",
        "a3":"6C",
        "a4":"1C"},

        {"question": "Which of the following has maximum number of unpaired electrons?",
        "image": "4.jpg",
        "correct": 2,
        "a1":"Cu^+",
        "a2":"Fe^2+",
        "a3":"Zn^+2",
        "a4":"Ni^3+"},

        {"question": "The strongest conjugate base is:",
        "image": "4.jpg",
        "correct": 2,
        "a1":"SO4^-",
        "a2":"CH3COO^-",
        "a3":"CL^-",
        "a4":"NO3^-"},

    ],
};
